# 端口号
server:
  port: 80

# 服务名
spring:
  application:
    name: service-gateway

# nacos服务地址
  cloud:
    nacos:
      server-addr: localhost:8848
    gateway:
      routes:
        - id: service-hosp
          uri: lb://service-hosp
          predicates:
            - Path=/*/hosp/**

        - id: service-cmn
          uri: lb://service-cmn
          predicates:
            - Path=/*/cmn/**

        - id: service-user
          uri: lb://service-user
          predicates:
            - Path=/*/user/**

        - id: service-msm
          uri: lb://service-msm
          predicates:
            - Path=/*/msm/**








