server:
  port: 8204

spring:
  application:
    name: service-msm
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8

  # redis配置
  redis:
    host: localhost
    port: 6379
    database: 0
    timeout: 3000000
    password: 123Aadm7
    lettuce:
      pool:
        max-active: 20
        max-wait: -1
        #最大阻塞等待时间(负数表示没限制)
        max-idle: 5
        min-idle: 0
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848

#rabbitmq地址
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

aliyun:
  sms:
    regionId: default
    accessKeyId: LTAI5tJBZmBzrNxM8pNAXYRa
    secret: 8XkcQqSDKobSLuHZM2aOwPhKeRF1cl
