# 服务端口
server:
  port: 8201

# 服务名
spring:
  application:
    name: service-hosp
# 环境设置: dev、test、prod
  profiles:
    active: dev
# mysql数据库连接
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/yygh_hosp?characterEncoding=utf8&useSSL=false
    username: root
    password: root
# 返回json的全局时间格式
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
# mongoDB
  data:
    mongodb:
      uri: mongodb://localhost:27017/OBryant

# 配置mapper xml文件的路径
mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
